apiVersion: v1
kind: Service
metadata:
  name: url-service
  namespace: tinyurl-prod
  labels:
    app: url-service
spec:
  selector:
    app: url-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: url-service-sa
  namespace: tinyurl-prod
  annotations:
    azure.workload.identity/client-id: $(URL_SERVICE_CLIENT_ID)
